AWSTemplateFormatVersion: 2010-09-09
Description: |
  Web Server of StackName
  
Parameters:
  

  
Mappings:
  
  
Resources:
  myApacheWebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-023eb5c021738c6d0
      InstanceType:  # To add
      KeyName: "String"   # To add
      SecurityGroupIds:    # To add
        SecurityGroupIds
      Tags: 
        - Name: Webserver
      Tenancy: "String"
      UserData: 
        Fn::Base64: |
        #!/bin/bash
        dnf update -y 
        dnf install httpd git -y 
        cd /home/ec2-user
        git clone 

        

  

  
Outputs: